import oracledb

def main():
    conn = None
    try:
        # 1. 연결 정보
        conn = oracledb.connect(
            user="system",          
            password="Asdf4156",    
            dsn="localhost:1521/freepdb1" 
        )
        conn.autocommit = True
        
        cur = conn.cursor()
        print("✅ 데이터베이스 연결 성공")

        def create_table(sql, name):
            try:
                cur.execute(sql)
                print(f"- {name} 테이블 생성 완료")
            except oracledb.DatabaseError as e:
                error_obj, = e.args
                if error_obj.code == 955:  # ORA-00955: name already used
                    print(f"- {name} 테이블 이미 존재 (생성 건너뜀)")
                else:
                    raise

        # 1. users
        create_table("""
            CREATE TABLE users (
                user_id       VARCHAR2(30) PRIMARY KEY,
                password      VARCHAR2(200) NOT NULL,
                nickname      VARCHAR2(50) UNIQUE NOT NULL,
                email         VARCHAR2(100) UNIQUE NOT NULL,
                profile_image VARCHAR2(255),
                created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
            )
        """, "users")

        # 2. followers
        create_table("""
            CREATE TABLE followers (
                follower_id  VARCHAR2(30) REFERENCES users(user_id),
                following_id VARCHAR2(30) REFERENCES users(user_id),
                PRIMARY KEY (follower_id, following_id)
            )
        """, "followers")

        # 3. user_tags
        create_table("""
            CREATE TABLE user_tags (
                user_id VARCHAR2(30) REFERENCES users(user_id),
                tag     VARCHAR2(50),
                PRIMARY KEY (user_id, tag)
            )
        """, "user_tags")

        # 4. Books (도서 정보) - [중요] 컬럼 길이 대폭 확장
        create_table("""
            CREATE TABLE Books (
                book_id VARCHAR2(20) PRIMARY KEY,
                isbn10 VARCHAR2(20),
                title VARCHAR2(1000) NOT NULL,    -- 200 -> 1000 확장
                author VARCHAR2(1000),            -- 200 -> 1000 확장 (에러 방지)
                publisher VARCHAR2(1000),         -- 200 -> 1000 확장
                published_at DATE,
                cover_image VARCHAR2(500),        -- URL이 길 수 있으므로 500으로 확장
                description CLOB,
                source VARCHAR2(20),
                created_at TIMESTAMP(6)
        )
        """, "Books")

        # 5. books_read (나중에 공개범위 설정을 위해 visibility 컬럼 추가 고려 가능)
        create_table("""
            CREATE TABLE books_read (
                user_id  VARCHAR2(30) REFERENCES users(user_id),
                book_id  VARCHAR2(20) REFERENCES books(book_id),
                read_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
                PRIMARY KEY (user_id, book_id)
            )
        """, "books_read")
        
        # 5.5 bookmarks
        create_table("""
            CREATE TABLE bookmarks (
                user_id     VARCHAR2(30) REFERENCES users(user_id) ON DELETE CASCADE,
                book_id     VARCHAR2(20) REFERENCES books(book_id) ON DELETE CASCADE,
                added_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
                PRIMARY KEY (user_id, book_id)
            )
        """, "bookmarks")

        # 6. ratings
        create_table("""
            CREATE TABLE ratings (
                user_id  VARCHAR2(30) REFERENCES users(user_id),
                book_id  VARCHAR2(20) REFERENCES books(book_id),
                rating   NUMBER(2,1) CHECK (rating BETWEEN 0.0 AND 5.0),
                PRIMARY KEY (user_id, book_id)
            )
        """, "ratings")

        # 7. reviews
        create_table("""
            CREATE TABLE reviews (
                review_id   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                user_id     VARCHAR2(30) REFERENCES users(user_id),
                book_id     VARCHAR2(20) REFERENCES books(book_id),
                content     VARCHAR2(1000),
                created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
            )
        """, "reviews")

        # 8. essays - [중요] is_public 컬럼 추가
        create_table("""
            CREATE TABLE essays (
                essay_id   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                user_id    VARCHAR2(30) REFERENCES users(user_id),
                book_id    VARCHAR2(20) REFERENCES books(book_id),
                title      VARCHAR2(255),
                content    CLOB,
                is_public  CHAR(1) DEFAULT 'Y',   -- 공개 여부 컬럼 추가 (app.py와 호환)
                created_at TIMESTAMP DEFAULT SYSTIMESTAMP
            )
        """, "essays")

        # 9. Events
        create_table("""
            CREATE TABLE Events (
                event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR2(255) NOT NULL,
                location VARCHAR2(255),
                start_date DATE,
                end_date DATE,
                description CLOB,
                source VARCHAR2(100)
        )
        """, "Events")

        # 10. Libraries
        create_table("""
            CREATE TABLE Libraries (
                library_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(255) NOT NULL,
                type VARCHAR2(50),
                location VARCHAR2(255),
                phone VARCHAR2(50),
                sns VARCHAR2(255),
                lon NUMBER,
                lat NUMBER
        )
        """, "Libraries")

        # 11. IndieBookstores
        create_table("""
            CREATE TABLE IndieBookstores (
                store_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(255) NOT NULL,
                address VARCHAR2(400),
                phone_number VARCHAR2(50),
                open_hours VARCHAR2(255),
                sns VARCHAR2(255),
                lat NUMBER,
                lon NUMBER,
                description CLOB,
                closed_day VARCHAR2(100)
        )
        """, "IndieBookstores")

        print("\n모든 테이블 생성 작업 완료 ✅")

    except oracledb.DatabaseError as e:
        print(f"❌ 데이터베이스 작업 중 오류 발생: {e}")
    finally:
        if conn:
            conn.close()
            print("데이터베이스 연결 해제 완료")

if __name__ == "__main__":
    main()